train:
  epochs: 20
  batch_size: 16
  num_workers: 16
  criterion: cross_entropy # available criterions are list in 'criterion_args' below
  loss_weight: null # null / balance / dynamic / list with shape num_classes. Weights for loss function. Don't use it with weighted sampling!
  loss_weight_decay_rate: 0 # if loss_weights is dynamic, loss weight will decay from balance to equivalent weights
  warmup_epochs: 0 # set to 0 to disable warmup
  metrics: [acc, f1, auc, precision, recall, kappa] # available metrics are list in utils.metrics
  indicator: auc # indicator for best model selection in validation set
  save_interval: 10 # the epoch interval of saving model
  eval_interval: 1 # the epoch interval of evaluating model on val dataset
  sample_view: false # save and visualize a batch of images on Tensorboard
  pin_memory: true # enables fast data transfer to CUDA-enabled GPUs
